@baseUrl = http://localhost:5000


# @name getAllFeedback
GET {{baseUrl}}/feedback
###
# @name getFeedbackByUsername
GET {{baseUrl}}/feedback/tungba
###
# @name deleteFeedbackByUsername
DELETE {{baseUrl}}/feedback/delete
Content-Type: application/json

{
    "username":"tungba3"
}
###
# @name createFeedback
POST {{baseUrl}}/feedback/create
Content-Type: application/json

{
    "username":"tungba",
    "content": "The product is so good"
}
###
# @name updateFeedback
PUT {{baseUrl}}/feedback/update
Content-Type: application/json

{
    "idFeedback":5,
    "content": "Feedback from tungba tungba"
}
###