@baseUrl = http://localhost:5000/api

#Account
# @name getAllAccount
GET {{baseUrl}}/account
###

# @name getAccountByUsername
GET {{baseUrl}}/account/tungba1
###
# @name deleteAccountByUsername
DELETE {{baseUrl}}/account/delete_by_username
Content-Type: application/json 

{
    "username": "tungba"
}
###
# @name createAccount
POST {{baseUrl}}/account/create
Content-Type: application/json

{
    "username" : "tungba",
    "password" : "1"
}
###
# @name updateAccountByUsername
PUT {{baseUrl}}/account/update_by_username
Content-Type: application/json

  {
    "username": "tungba1",
    "password": "1",
    "name": "Tung Ba 101",
    "image": "https://scontent.fhan14-2.fna.fbcdn.net/v/t39.30808-6/302171787_1812182202473423_2219482232048890630_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=enEAkEYByfoAX-FOwv9&_nc_ht=scontent.fhan14-2.fna&oh=00_AfDOZM0o2jIwjLuxV9sW3i_Tx7fwQoThEMCrWWeJpXEeRg&oe=639A87A2",
    "email": "tungba1@gmail.com",
    "phoneNumber": "0965899821",
    "gender": "Male",
    "dob": "2022-10-02"
  }
###
# @name getAllCategoryUser
GET {{baseUrl}}/category_user
###
# @name getCategoryUserByUsername
GET {{baseUrl}}/category_user/tungba
###
# @name deleteCategoryUserByUsername
DELETE {{baseUrl}}/category_user/delete_by_username 
Content-Type: application/json 

{
    "username" : "tungba"
}
###
# @name deleteCategoryUserItemByUsernameAndCuName
DELETE {{baseUrl}}/category_user/delete_by_username_and_cu_name
Content-Type: application/json 

{
    "username" : "tungba",
    "cuName" : "shirt"
}
###
# @name createCategoryUserItem
POST {{baseUrl}}/category_user/create 
Content-Type: application/json

{
    "username" : "tungba",
    "cuName" : "ball"
}
###

# @name getAllCart
GET {{baseUrl}}/cart
###
# @name getCartByUsername
{{baseUrl}}/cart/tungba
###
# @name getCartByIdCart
{{baseUrl}}/cart/1
###
# @name deleteCartByUsername
DELETE {{baseUrl}}/cart/delete_by_username
Content-Type: application/json 

{
    "username": "tungba2"
}
###
# @name deleteCartItemByUsernameAndIdProduct
DELETE {{baseUrl}}/cart/delete_by_username_and_id_product
Content-Type: application/json

{
    "username": "tungba2",
    "idProduct": 10
}
###
# @name createCart
POST {{baseUrl}}/cart/create
Content-Type: application/json

{
    "username": "tungba1",
    "idProduct": 2,
    "quantity": 2    
}
###
# @name updateQuantityByUsernameAndIdProduct
PUT {{baseUrl}}/cart/update_by_username_and_id_product 
Content-Type: application/json

{
    "username": "tungba",
    "idProduct": 10,
    "quantity": 4    
}
###