@baseUrl = http://localhost:5000/api


# @name getAllFeedback
GET {{baseUrl}}/feedback
###
# @name getFeedbackByUsername
GET {{baseUrl}}/feedback/tungba
###
# @name deleteFeedbackByUsername
DELETE {{baseUrl}}/feedback/delete_by_username
Content-Type: application/json

{
    "username":"tungba"
}
###
# @name deleteFeedbackByIdFeedback
DELETE {{baseUrl}}/feedback/delete_by_id_feedback
Content-Type: application/json

{
    "idFeedback":"6"
}
###
# @name createFeedback
POST {{baseUrl}}/feedback/create
Content-Type: application/json

{
    "username":"tungba3",
    "content": "The product is so good"
}
###
# @name updateFeedbackByIdFeedback
PUT {{baseUrl}}/feedback/update_by_id_feedback
Content-Type: application/json

{
    "idFeedback":6,
    "content": "Feedback from tungba tungba"
}
###