@baseUrl = http://localhost:5000/api

# @name getAllProduct
GET {{baseUrl}}/product
###

# @name getProductByType
GET {{baseUrl}}/product/filter/ball
###
# @name getProductByPriceRange
GET {{baseUrl}}/product/filter/20/20
###
# @name getProductByTypeAndPriceRange
GET {{baseUrl}}/product/filter/ball/10/20
###
# @name getProductSorted
GET {{baseUrl}}/product/filter/sort/only_sort/title/DESC
###
# @name getProductSortedByType
GET {{baseUrl}}/product/filter/sort/shirt/price/DESC
###
# @name getProductSortedByPriceRange
GET {{baseUrl}}/product/filter/sort/10/20/price/DESC
###
# @name getProductSortedByTypeAndPriceRange
GET {{baseUrl}}/product/filter/sort/socks/5/20/price/DESC
###

# @name getProductSearch
GET {{baseUrl}}/product/search/man
###
# @name getProductSearchByType
GET {{baseUrl}}/product/search/filter/arsenal/shirt
###
# @name getProductSearchByPriceRange
GET {{baseUrl}}/product/search/filter/arsenal/10/20
###
# @name getProductSearchByTypeAndPriceRange
GET {{baseUrl}}/product/search/filter/arsenal/shirt/10/20
###
# @name getProductSearchSorted
GET {{baseUrl}}/product/search/sort/arsenal/price/DESC
###
# @name getProductSearchSortedByType
GET {{baseUrl}}/product/search/sort/arsenal/shirt/price/DESC
###
# @name getProductSearchSortedByPriceRange
GET {{baseUrl}}/product/search/sort/arsenal/10/20/price/DESC
###
# @name getProductSearchSortedByTypeAndPriceRange
GET {{baseUrl}}/product/search/sort/arsenal/shirt/10/20/price/DESC
###

# @name getAllShirtProduct
GET {{baseUrl}}/product
###
# @name getProductByIdProduct
GET {{baseUrl}}/product/1
###
# @name deleteProductByIdProduct
DELETE  {{baseUrl}}/product/delete_by_id_product 
Content-Type: application/json

{
    "idProduct":"92"
}
###
# @name createProduct
POST {{baseUrl}}/product/create
Content-Type: application/json

{
    "title": "Demo",
    "price": 10,
    "image": "NF_ball.jpg",
    "description": "Nottingham Forest Football Club is an association football club based in West Bridgford, Nottinghamshire, England. The football club was founded in 1865 and have played their home games at the City Ground, on the banks of the River Trent, since 1898. Forest are one of four English clubs to have won the European Cup/UEFA Champions League more than once and are one of two English clubs to have won the competition back-to-back. Forest have two stars above their club crest to commemorate their two European Cup victories. The club competes in the Premier League, the top division of the English football league system.",
    "storage": 100,
    "sold": 0  
}
###
# @name updateProductInfoByIdProduct
PUT {{baseUrl}}/product/update_info_by_id_product
Content-Type: application/json

{
    "idProduct":98,
    "title": "Demo Product",
    "type": "shirt",
    "price": 10,
    "image": "NF_ball.jpg",
    "description": "Nottingham Forest Football Club is an association football club based in West Bridgford, Nottinghamshire, England. The football club was founded in 1865 and have played their home games at the City Ground, on the banks of the River Trent, since 1898. Forest are one of four English clubs to have won the European Cup/UEFA Champions League more than once and are one of two English clubs to have won the competition back-to-back. Forest have two stars above their club crest to commemorate their two European Cup victories. The club competes in the Premier League, the top division of the English football league system."
}
###
# @name updateProductStorageByIdProduct
PUT {{baseUrl}}/product/update_storage_by_id_product
Content-Type: application/json

{
    "idProduct":92,
    "storage": 10,
    "sold": 90
}
###


